// FPU_add_sub.v

// Generated using ACDS version 19.1 240

`timescale 1 ps / 1 ps
module FPU_add_sub (
		input  wire        clk,    //    clk.clk
		input  wire        areset, // areset.reset
		input  wire [31:0] a,      //      a.a
		input  wire [31:0] b,      //      b.b
		output wire [31:0] q,      //      q.q
		output wire [31:0] s       //      s.s
	);

	FPU_add_sub_altera_fp_functions_191_274fvhq fp_functions_0 (
		.clk    (clk),    //   input,   width = 1,    clk.clk
		.areset (areset), //   input,   width = 1, areset.reset
		.a      (a),      //   input,  width = 32,      a.a
		.b      (b),      //   input,  width = 32,      b.b
		.q      (q),      //  output,  width = 32,      q.q
		.s      (s)       //  output,  width = 32,      s.s
	);

endmodule
